name: CI

on:
  - pull_request
  - push

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Check file permissions
        run: ./dev-tools/check_file_permissions.sh

      - name: Check trailing whitespaces
        run: ./dev-tools/check_trailing_whitespaces.sh

      - name: Install dependencies
        run: composer update --no-progress

      - name: Analyse
        run: composer analyse

  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        php-version: [ '7.4', '8.0' ]
        include:
          - os: ubuntu-latest
            php-version: '7.2'
            composer_flags: '--prefer-lowest'
          - os: ubuntu-latest
            php-version: '7.2'
          - os: ubuntu-latest
            php-version: '7.3'
          - os: ubuntu-latest
            php-version: '7.4'
            dev_package: 'composer/composer:^1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo '::set-output name=dir::$(composer config cache-files-dir)'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-

      - name: Install dependencies
        run: composer update --no-progress ${{ matrix.composer_flags }}

      - name: Install dev package
        if: matrix.dev_package
        run: |
          composer config minimum-stability dev
          composer require "${{ matrix.dev_package }}" --prefer-stable --update-with-dependencies

      - name: Test
        run: composer test -- --coverage-clover=./build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.php-version == '7.4'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=./build/logs/clover.xml --verbose
