name: CI

on:
  - pull_request
  - push

jobs:
  analyse:
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        run: composer update --no-progress

      - name: Analyse
        run: composer self-update --preview; composer analyse

  test:
    name: PHP ${{ matrix.php-version }} ${{ matrix.description }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - description: 'with lowest dependencies'
            os: ubuntu-latest
            php-version: '7.4'
            composer-flags: '--prefer-lowest'
          - os: ubuntu-latest
            php-version: '7.4'
          - os: ubuntu-latest
            php-version: '8.1'
          - description: on macOS
            os: macos-latest
            php-version: '8.1'
          - description: on Windows
            os: windows-latest
            php-version: '8.1'
          - os: ubuntu-latest
            php-version: '8.2'
            composer-flags: '--ignore-platform-reqs'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo '::set-output name=dir::$(composer config cache-files-dir)'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-

      - name: Install dependencies
        run: composer update --no-progress ${{ matrix.composer-flags }}

      - name: Test
        run: composer test -- --coverage-clover=./build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.php-version == '8.1'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=./build/logs/clover.xml --verbose
